### PR TITLE
Automated installation process selection

### PR DESCRIPTION
**Pull request by PHATWalrus**
Automated installation process

### CODE REVIEW

**Comment by ShaDisNX255** [comment]
Looks pretty promising honestly, you already tested it? May include it in next update.

**Comment by PHATWalrus** [comment]
Logic seems to work fine in termux but fails in recovery

**Comment by PHATWalrus** [comment]
Can you check the indentation and shit

**Comment by PHATWalrus** [comment]
Fully functional now

**Comment by ShaDisNX255** [comment]
This is a mess. I'll take a look at your repo and sync accordingly

**Comment by PHATWalrus** [comment]
It's mostly a mess but a last few commits from https://github.com/ShaDisNX255/RayOS-S21FE-Port/pull/5/commits/a2db9c28bf4b71b2b3f041fdb72c45e86c85421a
Are good and useful rest are obsolete and just me Messing around like a dumass

**Pull request closed without merging**
